/*
 * ofxCuiCui.hpp
 *
 * Just a few UI elements (flat as grandma use to make)
 *
 * This code has been authored by Jules Françoise <jfrancoi@sfu.ca>
 * during his postdoc contract at Simon Fraser University (MovingStories
 * project).
 * See:
 *    http://julesfrancoise.com/
 *    http://movingstories.ca/
 *
 * Copyright (C) 2016 Jules Francoise.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef ofxofxCuiCuiButton_hpp
#define ofxofxCuiCuiButton_hpp

#include "components/ofxCuiCuiBpf.hpp"
#include "components/ofxCuiCuiButton.hpp"
#include "components/ofxCuiCuiCheckBox.hpp"
#include "components/ofxCuiCuiDraggableButton.hpp"
#include "components/ofxCuiCuiDropDown.hpp"
#include "components/ofxCuiCuiGroup.hpp"
#include "components/ofxCuiCuiMatrix.hpp"
#include "components/ofxCuiCuiMultiSlider.hpp"
#include "components/ofxCuiCuiNumbox.hpp"
#include "components/ofxCuiCuiShapeEditor.hpp"
#include "components/ofxCuiCuiSlider.hpp"
#include "components/ofxCuiCuiTextInput.hpp"
#include "core/ofxCuiCuiColormap.hpp"
#include "core/ofxCuiCuiCommon.hpp"
#include "core/ofxCuiCuiComponent.hpp"
#include "core/ofxCuiCuiGraph.hpp"
#include "core/ofxCuiCuiIcon.hpp"
#include "core/ofxCuiCuiStyle.hpp"
#include "core/ofxCuiCuiTextBox.hpp"

#pragma mark -
#pragma mark About

/**
 @mainpage About
 @anchor mainpage
 @brief ofxCuiCui is a collection of GUI components for OpenFrameworks.
 ofxCuiCui is dynamic, easy to use, and fully customizable.

 ![Image Alt](doc/doc-misc/screenshot.png)

 @author
 This code has been authored by <a href="http://julesfrancoise.com/"
 target="blank">Jules Françoise</a> during his postdoc contract at Simon Fraser
 University (<a href="http://movingstories.ca/" target="blank">MovingStories
 project</a>).

 @copyright Copyright (C) 2016 Jules Françoise.

 @par Licence
 This Source Code Form is subject to the terms of the Mozilla Public License, v.
 2.0. If a copy of the MPL was not distributed with this file, You can obtain
 one at http://mozilla.org/MPL/2.0/.
 */

#pragma mark -
#pragma mark Getting Started

/**
 @page GettingStarted Getting Started

 TODO...

 */

#pragma mark -
#pragma mark Documentation

/**
 @page Documentation Documentation

 This page contains the detailed documentation of the library (generated by
 Doxygen).

 <ul>
 <li><a href="modules.html">Modules</a></li>
 <li><a href="annotated.html">Class List</a></li>
 <li><a href="inherits.html">Class Hierarchy</a></li>
 </ul>

 */

#endif
