/*
 * ofxOui.hpp
 *
 * Just a few UI elements
 *
 * This code has been authored by Jules Francoise <jfrancoi@sfu.ca>
 * during his postdoc contract at Simon Fraser University (MovingStories
 * project).
 * See:
 *    http://julesfrancoise.com/
 *    http://movingstories.ca/
 *
 * Copyright (C) 2016 Jules Francoise.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef ofxofxOuiButton_hpp
#define ofxofxOuiButton_hpp

#include "components/ofxOuiBpf.hpp"
#include "components/ofxOuiButton.hpp"
#include "components/ofxOuiCheckBox.hpp"
#include "components/ofxOuiDraggableButton.hpp"
#include "components/ofxOuiDropDown.hpp"
#include "components/ofxOuiGroup.hpp"
#include "components/ofxOuiMatrix.hpp"
#include "components/ofxOuiMultiSlider.hpp"
#include "components/ofxOuiNumbox.hpp"
#include "components/ofxOuiShapeEditor.hpp"
#include "components/ofxOuiSlider.hpp"
#include "components/ofxOuiTextInput.hpp"
#include "components/ofxOuiWaveform.hpp"
#include "core/ofxOuiColormap.hpp"
#include "core/ofxOuiCommon.hpp"
#include "core/ofxOuiComponent.hpp"
#include "core/ofxOuiGraph.hpp"
#include "core/ofxOuiIcon.hpp"
#include "core/ofxOuiStyle.hpp"
#include "core/ofxOuiTextBox.hpp"

#pragma mark -
#pragma mark About

/**
 @mainpage About
 @anchor mainpage
 @brief ofxOui is a collection of GUI components for OpenFrameworks.
 ofxOui is dynamic, easy to use, and fully customizable.

 ![Image Alt](doc/doc-misc/screenshot.png)

 @author
 This code has been authored by <a href="http://julesfrancoise.com/"
 target="blank">Jules Francoise</a> during his postdoc contract at Simon Fraser
 University (<a href="http://movingstories.ca/" target="blank">MovingStories
 project</a>).

 @copyright Copyright (C) 2016 Jules Francoise.

 @par Licence
 This Source Code Form is subject to the terms of the Mozilla Public License, v.
 2.0. If a copy of the MPL was not distributed with this file, You can obtain
 one at http://mozilla.org/MPL/2.0/.
 */

#pragma mark -
#pragma mark Getting Started

/**
 @page GettingStarted Getting Started

 TODO...

 */

#pragma mark -
#pragma mark Documentation

/**
 @page Documentation Documentation

 This page contains the detailed documentation of the library (generated by
 Doxygen).

 <ul>
 <li><a href="modules.html">Modules</a></li>
 <li><a href="annotated.html">Class List</a></li>
 <li><a href="inherits.html">Class Hierarchy</a></li>
 </ul>

 */

#endif
